import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Providers from "@/redux/Provider";
import Footer from "@/components/Footer";
import SearchAndSelect from "@/components/SearchAndSelect";
import { AuthProviders } from "@/components/auth-providers";
import { Toaster } from "react-hot-toast";
import { PaginationComponent } from "@/components/PaginationComponent";
import PageInfoComponent from "@/components/PageInfoComponent";
import CheckboxComponent from "@/components/CheckboxComponent";
import { Suspense } from "react";

const roboto = Roboto({
  weight: ["400", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Test Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <AuthProviders>
          <Providers>
          <Suspense>
            <Header />
            <div className="container mx-auto children-wrapper">
                  
                  <CheckboxComponent />
                  <div className='pagination-container'>
                      <PageInfoComponent />
                      <PaginationComponent />
                  </div>
                  <SearchAndSelect />
                  <div>{children}</div>
                  <Toaster />
            </div>
            </Suspense>
          </Providers>
        </AuthProviders>
        <Footer />
      </body>
    </html>
  );
}
